services:
  rise-db:
    image: docker.io/library/mariadb:11
    restart: unless-stopped
    volumes:
      - rise_db_data:/var/lib/mysql
    env_file:
      - database.env
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10

  rise-server:
    build:
      context: ./src
      target: server
      args:
        API_BASE_URL: http://localhost:5000
    depends_on:
      rise-db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # Automatically applies EF Core migrations and seeds mock campus data
    env_file:
      - database.env
    ports:
      - "5000:8080"   # internal 8080, host 5000
    restart: unless-stopped

  rise-client:
    build:
      context: ./src
      target: client
      args:
        API_BASE_URL: http://localhost:3000
    container_name: rise-client
    depends_on:
      - rise-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "3000:80"     # host 3000, internal nginx 80
    restart: unless-stopped

volumes:
  rise_db_data:
