services:
  rise-db:
    image: mariadb:11
    restart: unless-stopped
    volumes:
      - rise_db_data:/var/lib/mysql
    env_file:
      - database.env
    ports:
     - 3306:3306

  rise-server:
    build:
      context: ./src
      target: server
      args:
        API_BASE_URL: http://localhost:5000
    depends_on:
      - rise-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # - ASPNETCORE_ENVIRONMENT=Development # Populates the database from Migration files (does not generate them)
    env_file:
      - database.env
    ports:
      - "5000:8080"   # intern 8080, extern 5000
    restart: unless-stopped

  rise-client:
    build:
      context: ./src
      target: client
      args:
        API_BASE_URL: http://localhost:3000
    container_name: rise-client
    depends_on:
      - rise-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "3000:80"     # extern 3000, intern 80
    restart: unless-stopped

volumes:
  rise_db_data:
