using Rise.Domain.News;

namespace Rise.Persistence.SeedData;

public static class NewsSeeder
{
    public static async Task Seed(ApplicationDbContext dbContext)
    {
        if (dbContext.NewsItems.Any())
            return;

        var newsItems = new List<NewsItem>
        {
            new NewsItem(
                "Auditorium krijgt naam van voormalig voorzitter",
                "Auditorium D op campus Schoonmeersen heet voortaan auditorium Paul Van Cauwenberge, naar de voormalige voorzitter van HOGENT, die vorige week zijn afscheid vierde na twaalf jaar voorzitterschap.",
                new List<string>
                {
                    "Het afscheid vond plaats op donderdag 2 oktober in het unieke kader van de Belvedère van de Boekentoren. De keuze voor die iconische ruimte van de universiteit Gent is niet toevallig: Paul Van Cauwenberge had er, voor hij voorzitter van HOGENT werd, al een respectabele carrière aan de universiteit op zitten: als internationaal gerenommeerd professor neus-keel-oor, als decaan van de faculteit Geneeskunde en Gezondheidswetenschappen en als rector (2005-2013).<br><br>Maar bovenal stond en staat Paul Van Cauwenberge bekend als een warm, empathisch en collegiaal persoon. Een bruggenbouwer die zoekt naar de gemeenschappelijke grond, veeleer dan naar de verschillen. Dat typeerde ook zijn voorzitterschap aan HOGENT. Gedurende twaalf jaar kon HOGENT rekenen op zijn volle engagement. Hij trad daarbij zelden op de voorgrond, maar was niettemin een altijd aanwezige en bereikbare voorzitter die zich ondersteunend opstelde. Hij heeft HOGENT en haar management steeds vertrouwen gegeven in het uitvoeren van hun taak.<br><br><strong style=\"color: black;\">Gella Vandecaveye</strong><br><br>Paul Van Cauwenberge gold ook als pleitbezorger voor meer sport en beweging. Zo was hij sportambassadeur van de Stad Gent, actief binnen de Europese en Vlaamse Federatie Bedrijfssporten en lid van de International Society of Olympic Historians. Hij speelde een baanbrekende rol - samen met toenmalige collega-rector Paul De Knop van de VUB - in de erkenning van het statuut van student-topsporter.<br><br>De directie, het personeel en de studenten van HOGENT danken Paul Van Cauwenberge van harte voor zijn jarenlange inzet!",
                    "Die sterke link met de sport werd tijdens de afscheidsplechtigheid in de verf gezet door de actieve inbreng van niemand minder dan ex-judoka Gella Vandecaveye, die tijdens haar sportloopbaan onder meer Olympisch zilver (Atlanta 1996) en brons (Sydney 2000) haalde. Haar viel de eer te beurt om het naambord van het auditorium Paul Van Cauwenberge te onthullen en aan de afscheidnemende voorzitter te overhandigen. Door een auditorium naar hem te noemen, is Paul Van Cauwenberge nooit meer helemaal weg uit HOGENT."
                }
                ,
                new List<string>
                {
                    "https://www.hogent.be/sites/hogent/assets/paulvancau_en_gella_vdc.png",
                },
                DateTime.Now.AddDays(-2)
            ),
            new NewsItem(
                "Studentenraad Organiseert Kerstmarkt",
                "Op 15 december vindt de jaarlijkse kerstmarkt plaats op Campus Mercator met lokale standjes en entertainment.",
                new List<string>
                {
                    "De studentenraad van HOGENT heeft het genoegen om aan te kondigen dat de jaarlijkse kerstmarkt dit jaar plaatsvindt op <strong style=\"color: black;\">15 december 2025 van 11:00 tot 19:00 uur</strong> op <strong style=\"color: black;\">Campus Mercator</strong>. Deze traditie, die inmiddels al vijf jaar bestaat, is uitgegroeid tot één van de meest gewaardeerde evenementen van het academiejaar. De kerstmarkt biedt studenten, medewerkers en buurtbewoners de kans om samen te komen in een warme, gezellige sfeer en het einde van het semester te vieren.<br><br>De campus zal worden getransformeerd in een winterwonderland met sfeervolle kerstverlichting, een grote kerstboom en gezellige chalets waar lokale handelaars en studenteninitiatieven hun waren aanbieden. Dit jaar verwachten we meer dan 25 verschillende standjes, waaronder ambachtelijke juwelen, handgemaakte kerstversiering, natuurlijke cosmetica en unieke geschenkideeën. Perfect om je kerstcadeaus te kopen terwijl je lokale ondernemers steunt!",
                    "<strong style=\"color: black;\">Culinair Genieten</strong><br><br>Naast het winkelaanbod kun je op de kerstmarkt genieten van een breed scala aan culinaire lekkernijen. Van traditionele glühwein en warme chocomelk tot verse wafels, oliebollen en gebrande kastanjes. Verschillende studentenverenigingen nemen deel met hun eigen foodkraampjes, waaronder de populaire raclette-stand van de Studentenclub Mercator en de churros-kraam van de internationale studenten. Voor wie het graag vegetarisch of vegan houdt, zijn er dit jaar ook extra opties voorzien, waaronder een volledige plantaardige foodtruck.<br><br>Nieuw dit jaar is de 'Taste of the World' corner, waar internationale studenten traditionele kerstgerechten uit hun thuisland delen. Proef Poolse pierogi, Duitse lebkuchen, Spaanse turron en nog veel meer. Het is een prachtige gelegenheid om de culturele diversiteit van onze campus te vieren.",
                    "<strong style=\"color: black;\">Entertainment en Activiteiten</strong><br><br>Gedurende de hele dag is er live entertainment voorzien. Het HOGENT studentenkoor opent de kerstmarkt om 11:30 uur met een selectie klassieke en moderne kerstliederen. Verschillende studentenbands treden op gedurende de middag, waaronder de bekroonde coverband 'The Academics' en de jazzy klanken van 'Smooth Operators'. Om 17:00 uur vindt het hoogtepunt plaats: de officiële aansteking van de grote kerstboom, begeleid door een verrassingsoptreden.<br><br>Voor de kinderen (en het kind in onszelf) is er een leuke workshop kerstversieringen maken, een foto-hoek met de kerstman en een nostalgische draaimolen. De opbrengst van alle activiteiten gaat naar twee goede doelen: vzw Student & Handicap, die studenten met een beperking ondersteunt, en de HOGENT Solidariteitsfonds dat studenten in financiële nood helpt. Samen maken we het verschil!"
                },
                new List<string>
                {
                    "https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=800",
                    "https://images.unsplash.com/photo-1482517967863-00e15c9b44be?w=800"
                },
                DateTime.Now.AddDays(-5)
            ),
            new NewsItem(
                "Nieuwe Online Platform voor Stage-opdrachten",
                "Het nieuwe stage-platform maakt het eenvoudiger voor studenten om stage-opdrachten te vinden en te solliciteren.",
                new List<string>
                {
                    "HOGENT heeft een gloednieuw online platform gelanceerd dat speciaal is ontworpen om studenten te helpen bij het vinden van de perfecte stage-opdracht. Het 'HOGENT Stage Portal' is het resultaat van twee jaar ontwikkeling in samenwerking met het studenten-IT-team, de stagecoördinatoren en feedback van meer dan 500 studenten en 100 stagebedrijven. Het platform biedt een overzichtelijke, gebruiksvriendelijke database van beschikbare stages bij verschillende bedrijven en organisaties in binnen- en buitenland.<br><br>De ontwikkeling van dit platform was hard nodig. Volgens het meest recente onderzoek besteedden studenten gemiddeld 40 uur aan het zoeken naar een geschikte stage-opdracht, verspreid over verschillende websites, mailwisselingen en telefoonconversaties. Met het nieuwe platform wordt deze zoektijd naar verwachting met meer dan 60% gereduceerd. Het systeem centraliseert alle stage-informatie en maakt het sollicitatieproces transparanter en efficiënter voor alle betrokken partijen.",
                    "<strong style=\"color: black;\">Functionaliteiten voor Studenten</strong><br><br>Studenten kunnen eenvoudig een persoonlijk profiel aanmaken waarin ze hun studierichting, competenties, interesses en beschikbaarheid aangeven. Het uploaden van een CV en motivatiebrief gebeurt met één klik, en deze documenten kunnen hergebruikt worden voor meerdere sollicitaties. Een slim matchingssysteem analyseert je profiel en beveelt automatisch passende stage-opdrachten aan op basis van je voorkeuren en kwalificaties.<br><br>Het dashboard geeft een helder overzicht van al je sollicitaties, met real-time updates over de status: ontvangen, in behandeling, uitgenodigd voor gesprek, of afgewezen. Je ontvangt automatische notificaties via e-mail en de HOGENT-app wanneer er nieuwe relevante stages beschikbaar komen of wanneer een bedrijf reageert op je sollicitatie. Daarnaast kun je bedrijven die je interessant vindt opslaan in een favorietenlijst en alerts instellen voor specifieke sectoren of functies.",
                    "<strong style=\"color: black;\">Voordelen voor Bedrijven en Organisaties</strong><br><br>Ook bedrijven profiteren enorm van het nieuwe platform. Ze kunnen kosteloos stage-vacatures plaatsen, een bedrijfsprofiel aanmaken met foto's en video's, en direct communiceren met geïnteresseerde studenten. Het platform helpt hen om de juiste kandidaten te vinden door geavanceerde filteropties op studierichting, competenties en beschikbaarheid. Bedrijven kunnen sollicitaties efficiënt beheren, kandidaten beoordelen en uitnodigen voor gesprekken, alles binnen één systeem.<br><br>Meer dan 200 bedrijven hebben zich al aangesloten, waaronder bekende namen zoals Volvo Cars Gent, AZ Maria Middelares, stad Gent, en verschillende innovatieve start-ups. Het platform wordt ook actief gepromoot bij nieuwe partners tijdens de jaarlijkse HOGENT Business Networking events. Het stage-platform is nu beschikbaar voor alle studenten via de studentenportal onder het tabblad 'Stage & Carrière'. Uitgebreide handleidingen, tutorial video's en een FAQ-sectie zijn beschikbaar. Bij vragen kunnen studenten terecht bij de stagecoördinator van hun opleiding of de servicedesk via stageportal@hogent.be."
                },
                new List<string>
                {
                    "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800",
                    "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800"
                },
                DateTime.Now.AddDays(-7)
            ),
            new NewsItem(
                "Sportdag: Schrijf Je Nu In!",
                "De jaarlijkse sportdag komt eraan! Schrijf je in voor verschillende sportactiviteiten en win geweldige prijzen.",
                new List<string>
                {
                    "Op <strong style=\"color: black;\">10 maart 2026</strong> organiseren we de achtste editie van de jaarlijkse <strong style=\"color: black;\">HOGENT Sportdag</strong>, het grootste sportevenement van het academiejaar. Vorig jaar namen meer dan 800 studenten en medewerkers deel aan deze fantastische dag vol beweging, competitie en gezelligheid. De Sportdag is veel meer dan een sportwedstrijd – het is een viering van teamgeest, gezonde levensstijl en de diverse HOGENT-gemeenschap.<br><br>Of je nu een doorgewinterde sporter bent of gewoon eens iets actiefs wilt doen met vrienden, de Sportdag biedt voor iedereen iets. Het evenement vindt plaats in en rond de moderne sportfaciliteiten van Campus Schoonmeersen, die vorig jaar nog werden gerenoveerd en uitgebreid met state-of-the-art apparatuur. De dag staat in het teken van fair play, plezier en het ontdekken van nieuwe sporten en talenten.",
                    "<strong style=\"color: black;\">Sportactiviteiten en Toernooien</strong><br><br>Er zijn dit jaar maar liefst 12 verschillende sportactiviteiten beschikbaar: voetbal (5-tegen-5), basketbal (3-tegen-3), volleybal, badminton, tafeltennis, padel, en zelfs een spectaculaire obstacle course die speciaal voor dit evenement wordt opgebouwd. Nieuw dit jaar zijn ook workshops yoga, zumba en kickboksen voor wie liever individueel actief is. De obstacle course, een van de absolute publieksfavorieten, bestaat uit 15 uitdagende obstakels waaronder een klimwand, balanceerbalken, touwklim en een modderpit.<br><br>Je kunt je inschrijven als individu of als team (minimaal 4, maximaal 8 personen). Teams kunnen bestaan uit studenten van verschillende opleidingen – een perfecte manier om nieuwe mensen te leren kennen! Voor elke sport worden er toernooien georganiseerd in verschillende niveaus: recreatief en competitief, zodat iedereen op zijn eigen niveau kan deelnemen. De winnaars van elk toernooi ontvangen niet alleen eeuwige roem, maar ook fantastische prijzen gesponsord door lokale sportwinkel Decathlon en fitnesscentrum Basic-Fit.",
                    "<strong style=\"color: black;\">Programma en Praktische Info</strong><br><br>De deuren openen om 08:30 uur met een energieke warming-up sessie begeleid door professionele fitnessinstructeurs. Om 09:00 uur starten de eerste wedstrijden en workshops. Gedurende de hele dag kun je deelnemen aan verschillende activiteiten – het schema wordt flexibel ingepland zodat je meerdere sporten kunt uitproberen. Om 12:30 uur is er een lunchpauze waarin gezonde maaltijden, fruitsmoothies en energierepen worden aangeboden. Om 15:30 uur vinden de finales plaats van alle toernooien, gevolgd door de prijsuitreiking om 16:30 uur.<br><br>Deelname is volledig gratis! In de prijs inbegrepen zijn: toegang tot alle faciliteiten, sportmateriaal, lunch, versnaperingen en drankjes gedurende de hele dag, en een goodie bag met sportproducten en kortingsbonnen. Inschrijvingen zijn nu open via de HOGENT Sport App of bij de sportdienst (lokaal A.0.12, Campus Schoonmeersen). Wees er snel bij want het aantal plaatsen is beperkt en vorig jaar waren we binnen twee weken volgeboekt! Schrijf je vóór <strong style=\"color: black;\">1 maart 2026</strong> in en ontvang een gratis HOGENT sportshirt. Meer info: sport@hogent.be of 09 243 23 15."
                },
                new List<string>
                {
                    "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800",
                    "https://images.unsplash.com/photo-1517649763962-0c623066013b?w=800"
                },
                DateTime.Now.AddDays(-10)
            ),
            new NewsItem(
                "Gastcollege: AI in de Praktijk",
                "Topexpert uit de industrie geeft gastcollege over de toepassingen van Artificial Intelligence in moderne bedrijven.",
                new List<string>
                {
                    "Aanstaande woensdag 6 december hebben we het bijzondere genoegen om <strong style=\"color: black;\">Dr. Sarah Van den Berg</strong> te verwelkomen aan HOGENT. Dr. Van den Berg is een internationaal erkende AI-specialist en Chief Technology Officer bij ML-Innovations, een vooraanstaand Belgisch technologiebedrijf dat gespecialiseerd is in kunstmatige intelligentie en machine learning oplossingen. Met een doctoraat in computerwetenschappen van de KU Leuven en meer dan 15 jaar ervaring in de tech-industrie, heeft ze aan talrijke baanbrekende AI-projecten gewerkt voor bedrijven zoals Microsoft, IBM en verschillende Europese start-ups.<br><br>Dr. Van den Berg staat bekend om haar vermogen om complexe technische concepten toegankelijk te maken voor diverse doelgroepen. Ze is regelmatig spreker op internationale conferenties, heeft meer dan 40 wetenschappelijke publicaties op haar naam staan, en werd in 2024 uitgeroepen tot 'Tech Woman of the Year' door Data News. Haar missie is om de kloof te dichten tussen academische AI-research en praktische toepassingen in het bedrijfsleven.",
                    "<strong style=\"color: black;\">Inhoud van het Gastcollege</strong><br><br>Tijdens dit boeiende gastcollege zal Dr. Van den Berg dieper ingaan op de praktische toepassingen van Artificial Intelligence in het moderne bedrijfsleven. Ze zal concrete use cases bespreken uit verschillende sectoren, van machine learning in productieprocessen en voorspellende analyses in de logistiek, tot natural language processing in klantenservice en computervisie in de gezondheidszorg. Aan de hand van echte projectvoorbeelden waar ze zelf aan heeft gewerkt, krijg je inzicht in hoe AI-systemen worden ontwikkeld, getraind en geïmplementeerd.<br><br>Een belangrijk onderdeel van de presentatie is gewijd aan de ethische aspecten en verantwoordelijkheden die komen kijken bij het gebruik van AI. Dr. Van den Berg zal discussiëren over thema's zoals algoritmische bias, privacy concerns, transparantie en de impact van AI op de arbeidsmarkt. Ze deelt best practices over hoe bedrijven verantwoord kunnen omgaan met deze technologie en hoe ze ethische richtlijnen kunnen integreren in hun AI-strategie. Tot slot zal ze ook ingaan op toekomstige trends en carrièremogelijkheden in het AI-landschap.",
                    "<strong style=\"color: black;\">Praktische Informatie en Inschrijving</strong><br><br>Het gastcollege is toegankelijk voor alle studenten en medewerkers van HOGENT, ongeacht studierichting. Hoewel de focus ligt op technologische toepassingen, is geen voorkennis van AI of programmeren vereist – Dr. Van den Berg zal zorgen dat iedereen de presentatie kan volgen. Na de presentatie is er een uitgebreide Q&A-sessie waarin je al je vragen kunt stellen, gevolgd door een informele netwerkmoment met koffie en taart. Dit is een unieke kans om in contact te komen met een topper uit de industrie en misschien zelfs te praten over stage- of jobbmogelijkheden.<br><br><strong style=\"color: black;\">Datum:</strong> woensdag 6 december 2025<br><strong style=\"color: black;\">Tijd:</strong> 14:00 - 16:00 uur (netwerkmoment tot 16:30)<br><strong style=\"color: black;\">Locatie:</strong> Auditorium A2.1, Campus Schoonmeersen<br><strong style=\"color: black;\">Inschrijving:</strong> Verplicht via events@hogent.be (vermeld je naam, opleiding en studentennummer)<br><strong style=\"color: black;\">Deadline inschrijving:</strong> 4 december 2025<br><br>Het aantal plaatsen is beperkt tot 200 personen, dus schrijf je snel in! Ingeschreven deelnemers ontvangen een dag voor het event een bevestigingsmail met het volledige programma en een digitaal informatiepakket over AI."
                },
                new List<string>
                {
                    "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800",
                    "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800"
                },
                DateTime.Now.AddDays(-14)
            ),
            new NewsItem(
                "Examenrooster Bekend",
                "Het examenrooster voor de januari-examens is nu beschikbaar op het studentenportaal.",
                new List<string>
                {
                    "Het examenrooster voor de <strong style=\"color: black;\">januari-examenperiode</strong> is vandaag gepubliceerd en kan geraadpleegd worden via het <strong style=\"color: black;\">studentenportaal</strong>. Studenten worden gevraagd om hun persoonlijk examenrooster grondig te controleren en eventuele conflicten onmiddellijk te melden bij het studentensecretariaat.",
                    "<strong style=\"color: black;\">Belangrijke data:</strong>\n- <strong style=\"color: black;\">Examenperiode:</strong> 08/01/2026 tot 26/01/2026\n- <strong style=\"color: black;\">Laatste dag voor bezwaar:</strong> 02/12/2025\n- <strong style=\"color: black;\">Resultaten beschikbaar:</strong> uiterlijk 02/02/2026",
                    "Vergeet niet om je <strong style=\"color: black;\">geldig studentenbewijs en identiteitskaart</strong> mee te brengen naar elk examen. Kom minstens <strong style=\"color: black;\">15 minuten</strong> voor aanvang van het examen toe.",
                    "Veel succes met de voorbereidingen!"
                },
                new List<string>
                {
                    "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800",
                    "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800"
                },
                DateTime.Now.AddDays(-3)
            ),
            new NewsItem(
                "Internationale Week: Ontdek de Wereld",
                "Van 20 tot 24 februari organiseren we de Internationale Week met activiteiten, presentaties en culinaire ontdekkingen.",
                new List<string>
                {
                    "HOGENT viert diversiteit en internationale verbondenheid tijdens de <strong style=\"color: black;\">Internationale Week</strong> van <strong style=\"color: black;\">20 tot 24 februari 2026</strong>! Deze jaarlijkse traditie, die dit jaar haar tiende editie beleeft, staat volledig in het teken van internationale samenwerking, culturele uitwisseling en het ontdekken van andere culturen. Alle campussen worden getransformeerd in een internationale ontmoetingsplaats waar studenten, docenten en bezoekers kunnen genieten van een breed scala aan activiteiten, presentaties en culinaire ontdekkingen.<br><br>HOGENT verwelkomt jaarlijks meer dan 1.200 internationale studenten uit 60 verschillende landen, en tijdens de Internationale Week krijgen ze de kans om hun thuiscultuur te delen met de rest van de HOGENT-gemeenschap. Tegelijkertijd biedt het evenement Belgische studenten de mogelijkheid om kennis te maken met internationale kansen, zoals Erasmus-uitwisselingen, internationale stages en andere mobiliteitsprogramma's. Het is een week vol inspiratie, ontdekking en verbinding die verder reikt dan de klaslokalen.",
                    "<strong style=\"color: black;\">Dagelijks Programma Hoogtepunten</strong><br><br><strong style=\"color: black;\">Maandag:</strong> De week wordt feestelijk geopend om 10:00 uur in de grote aula met welkomstwoorden van de directie, gevolgd door spectaculaire culturele optredens. Verwacht traditionele dans uit India, Afrikaanse drums, Latijns-Amerikaanse salsa en nog veel meer. In de namiddag zijn er speed-networking sessies waar je internationale studenten kunt ontmoeten.<br><br><strong style=\"color: black;\">Dinsdag:</strong> Deze dag staat volledig in het teken van mobiliteit. Er zijn uitgebreide Erasmus+ informatiesessies waarin je alles te weten komt over studeren in het buitenland, beschikbare bestemmingen, aanvraagprocedures en financiering. Alumni die in het buitenland hebben gestudeerd delen hun ervaringen in inspirerende paneldiscussies.<br><br><strong style=\"color: black;\">Woensdag:</strong> Het hoogtepunt van de week! De internationale studentenmarkt vindt plaats op de centrale campus met meer dan 40 stands van verschillende landen. Elke stand toont culturele objecten, foto's, informatieve posters en typische souvenirs. Studenten kunnen hun paspoort laten stempelen bij elke stand en maken kans op fantastische prijzen.<br><br><strong style=\"color: black;\">Donderdag:</strong> Culinaire dag! De World Food Court biedt authentieke gerechten uit meer dan 25 landen. Proef Vietnamese loempia's, Marokkaanse couscous, Braziliaanse feijoada, Japanse sushi, Griekse gyros en nog veel meer. Alle gerechten worden bereid door internationale studenten zelf.<br><br><strong style=\"color: black;\">Vrijdag:</strong> De week wordt afgesloten met een internationaal filmfestival. Er worden films vertoond uit verschillende landen (met Nederlandse ondertiteling), gevolgd door discussies over de culturele thema's.",
                    "<strong style=\"color: black;\">Workshops en Extra Activiteiten</strong><br><br>Naast het hoofdprogramma zijn er gedurende de hele week diverse workshops waar je kunt deelnemen: taalworkshops (leer de basis van Spaans, Chinees, Arabisch of Zweeds), kookworkshops waarin je traditionele gerechten leert bereiden, kunstworkshops (kalligrafie, henna, origami), en muziekworkshops met exotische instrumenten. Er zijn ook informatiesessies over internationale stages, vrijwilligerswerk in het buitenland en internationale carrièrekansen.<br><br>Voor een ludieke twist organiseert de studentenraad een 'Global Quiz Night' op woensdagavond, waarbij teams van studenten (mix van Belgen en internationals) strijden om de titel van 'World Champion'. Alle activiteiten zijn volledig gratis toegankelijk voor studenten en personeel. Het volledige programma met tijdstippen en locaties wordt begin februari gepubliceerd op de HOGENT-website en via de studentenapp. Schrijf deze week alvast in je agenda – je wilt dit niet missen! Voor meer informatie: international@hogent.be"
                },
                new List<string>
                {
                    "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800",
                },
                DateTime.Now.AddDays(-20)
            ),
            new NewsItem(
                "Nieuwe Fietsenstalling Geopend",
                "Campus Mercator beschikt nu over een overdekte fietsenstalling met plaats voor 300 fietsen.",
                new List<string>
                {
                    "Fantastisch nieuws voor alle fietsers! De gloednieuwe <strong style=\"color: black;\">overdekte fietsenstalling</strong> op <strong style=\"color: black;\">Campus Mercator</strong> is officieel geopend en staat vanaf vandaag ter beschikking van alle studenten en medewerkers. Deze moderne faciliteit is het resultaat van maandenlange planning en bouw, en vormt een belangrijk onderdeel van het duurzaamheidsbeleid van HOGENT. De stalling biedt plaats aan maar liefst <strong style=\"color: black;\">300 fietsen</strong> en is voorzien van alle moderne gemakken die je als fietser nodig hebt.<br><br>Het project kwam tot stand na herhaaldelijke verzoeken van de studentenraad en feedback uit de jaarlijkse tevredenheidsenquête, waarin veel studenten aangaven dat de bestaande fietsenrekken onvoldoende waren en dat hun fietsen vaak nat werden of beschadigd raakten. Met deze investering van 180.000 euro laat HOGENT zien dat duurzame mobiliteit serieus wordt genomen. Fietsen naar de campus wordt nu nog aantrekkelijker, veiliger en comfortabeler.",
                    "<strong style=\"color: black;\">State-of-the-art Faciliteiten</strong><br><br>De nieuwe fietsenstalling is veel meer dan een simpele overdekte parking. Het moderne gebouw biedt volledige bescherming tegen weer en wind dankzij een stevig dak en zijwanden, terwijl goede ventilatie ervoor zorgt dat fietsen snel drogen na een regenbui. De LED-verlichting met bewegingssensoren garandeert goede zichtbaarheid, zelfs in de donkere wintermaanden, en bespaart tegelijkertijd energie.<br><br>Voor extra veiligheid is de volledige stalling uitgerust met <strong style=\"color: black;\">24/7 camerabewaking</strong>, gekoppeld aan het centrale beveiligingssysteem van de campus. Alle fietsen kunnen worden vastgemaakt aan stevige fietsenrekken, en er is voldoende ruimte tussen de rekken zodat je je fiets gemakkelijk kunt parkeren zonder andere fietsen te beschadigen. Speciaal voor eigenaren van elektrische fietsen en speed pedelecs zijn er <strong style=\"color: black;\">20 oplaadpunten</strong> geïnstalleerd, waar je gratis je batterij kunt opladen terwijl je in de les zit.",
                    "<strong style=\"color: black;\">Fietsherstel en Praktische Info</strong><br><br>Een unieke toevoeging is het <strong style=\"color: black;\">zelf-service fietsherstelpunt</strong> in de hoek van de stalling. Hier vind je basisgereedschap zoals schroevendraaiers, bandenlichters, pompen, smeermiddel en zelfs een werkstandaard om je fiets op te tillen. Perfect voor kleine reparaties of om snel je band op te pompen voordat je naar huis fietst. Er hangen ook instructieposters met tips voor simpel fietsonderhoud.<br><br>De toegang tot de stalling is volledig <strong style=\"color: black;\">gratis</strong> voor alle studenten en medewerkers met een geldige HOGENT-campuskaart. Je scant je kaart bij de toegangspoort en de deur opent automatisch. De stalling is toegankelijk van <strong style=\"color: black;\">6:00 tot 23:00 uur</strong> op weekdagen en van 8:00 tot 20:00 uur in het weekend. Voor noodgevallen buiten deze uren kun je contact opnemen met de bewaking.<br><br>De locatie van de nieuwe stalling is ideaal: direct naast de hoofdingang van Campus Mercator, op minder dan 50 meter van de aula en cafetaria. Fiets veilig, duurzaam en comfortabel naar de campus – je fiets verdient het! Voor vragen of opmerkingen: facilities@hogent.be"
                },
                new List<string>
                {
                    "https://images.unsplash.com/photo-1571333250630-f0230c320b6d?w=800",
                    "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800"
                },
                DateTime.Now.AddDays(-12)
            ),
            new NewsItem(
                "Mentorprogramma: Word Mentor of Mentee",
                "Schrijf je in voor het mentorprogramma en help nieuwe studenten op weg, of laat je zelf begeleiden!",
                new List<string>
                {
                    "Het bewezen succesvolle <strong style=\"color: black;\">HOGENT Mentorprogramma</strong> gaat opnieuw van start! Dit peer-to-peer begeleidingsprogramma, dat sinds 2019 loopt en inmiddels meer dan 2.500 studenten heeft geholpen, koppelt ervaren studenten (mentoren uit het tweede jaar of hoger) aan eerstejaars of nieuwe studenten (mentees) om hen te ondersteunen bij hun start op de hogeschool. De transitie naar het hoger onderwijs kan voor veel studenten overweldigend zijn – nieuwe omgeving, andere studiemethodes, zelfstandig leven, nieuwe sociale kringen. Het mentorprogramma biedt een veilige en ondersteunende omgeving waarin nieuwe studenten zich sneller thuis voelen en beter presteren.<br><br>Onderzoek toont aan dat studenten die deelnemen aan het mentorprogramma een significant hogere slaagkans hebben (88% tegenover 76% gemiddeld) en zich sneller verbonden voelen met de hogeschool. Ze ervaren minder stress, hebben een beter zicht op studiestrategieën en bouwen waardevolle sociale netwerken op. Voor mentoren biedt het programma de kans om leiderschapsvaardigheden te ontwikkelen, bij te dragen aan de gemeenschap en iets terug te geven aan de volgende generatie studenten.",
                    "<strong style=\"color: black;\">Word Mentor – Maak Het Verschil</strong><br><br>Als <strong style=\"color: black;\">mentor</strong> speel je een cruciale rol in het welzijn en succes van nieuwe studenten. Je helpt hen wegwijs te worden op de campus (waar zijn de lokalen, bibliotheek, cafetaria?), beantwoordt vragen over het studentenleven (welke studentenverenigingen zijn er, waar vind je betaalbaar eten, hoe balanceer je studie en vrije tijd?), en deelt je eigen ervaringen en studietips. Je bent geen academische begeleider of docent – dat hoeft ook niet. Je bent gewoon een vriendelijke, toegankelijke ouderejaars die zich nog herinnert hoe het was om nieuw te zijn.<br><br>Het mentorschap vraagt niet veel tijd: gemiddeld 2 uur per maand, flexibel in te vullen. Jullie kunnen afspreken voor een koffie, samen lunchen, een rondleiding geven of gewoon online chatten. Het is een laagdrempelige maar betekenisvolle vorm van ondersteuning. Het mooiste? Je ontwikkelt automatisch waardevolle <strong style=\"color: black;\">soft skills</strong> zoals empathie, communicatie, probleemoplossend denken en coaching – competenties die werkgevers hoog waarderen. Bovendien leer je nieuwe mensen kennen, vergroot je je netwerk en ervaar je de voldoening van het helpen van anderen.",
                    "<strong style=\"color: black;\">Word Mentee – Krijg De Steun Die Je Nodig Hebt</strong><br><br>Als <strong style=\"color: black;\">mentee</strong> krijg je een ervaren student toegewezen die jou persoonlijk begeleidt gedurende je eerste semester (en langer indien gewenst). Je mentor is je aanspreekpunt voor alle praktische vragen: waar moet ik zijn voor mijn eerste les? Hoe werkt Chamilo? Welke boeken moet ik kopen? Maar ook voor minder tastbare zaken: hoe maak ik nieuwe vrienden? Hoe ga ik om met heimwee? Hoe plan ik mijn studietijd effectief? Je mentor heeft zelf recent dezelfde uitdagingen doorgemaakt en begrijpt precies wat je meemaakt.<br><br>De relatie is vrijblijvend en vertrouwelijk. Jij bepaalt hoe intensief het contact is en welke onderwerpen je wilt bespreken. Sommige mentor-mentee koppels ontmoeten elkaar wekelijks, anderen communiceren voornamelijk via WhatsApp. Het belangrijkste is dat je iemand hebt waar je terecht kunt met vragen, groot of klein. Veel mentees geven aan dat hun mentor de sleutel was tot een geslaagde start van hun hogeschoolcarrière.",
                    "<strong style=\"color: black;\">Ondersteuning en Voordelen</strong><br><br>HOGENT ondersteunt alle deelnemers met professionele begeleiding. Mentoren krijgen voorafgaand aan het programma een verplichte <strong style=\"color: black;\">workshop</strong> over effectief mentorschap, actief luisteren, grenzen stellen en het herkennen van signalen van studiestress of mentale problemen. Gedurende het jaar zijn er optionele verdiepingsworkshops over thema's zoals interculturele communicatie, timemanagement coaching en motivatietechnieken. Een dedicated programmcoördinator is altijd bereikbaar voor vragen of ondersteuning.<br><br><strong style=\"color: black;\">Concrete voordelen voor mentoren:</strong><br>- Officieel <strong style=\"color: black;\">certificaat</strong> bij succesvol afronden (geweldig voor je CV!)<br>- Gratis workshops over persoonlijke ontwikkeling en soft skills<br>- Uitnodiging voor exclusieve netwerkevents<br>- Vermelding op LinkedIn en referentie voor toekomstige werkgevers<br>- Kans om deel te nemen aan het 'Mentor van het Jaar' award programma<br>- Bijdragen aan een zinvolle community<br><br>Inschrijven kan tot <strong style=\"color: black;\">15 december 2025</strong> via het studentenportaal onder het tabblad 'Mentorprogramma'. Na inschrijving volgt een kort intakegesprek en dan worden de koppels gemaakt op basis van studierichting, interesses en persoonlijkheid. Het programma start officieel in de eerste week van februari 2026 met een kick-off event waar alle mentoren en mentees elkaar ontmoeten. Meer info: mentoring@hogent.be of 09 243 23 67."
                },
                new List<string>
                {
                    "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800",
                    "https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?w=800"
                },
                DateTime.Now.AddDays(-8)
            ),
            new NewsItem(
                "Duurzaamheidsproject: HOGENT Goes Green",
                "HOGENT lanceert nieuw duurzaamheidsproject met als doel om de campussen klimaatneutraal te maken tegen 2030.",
                new List<string>
                {
                    "HOGENT neemt een grote stap voorwaarts in duurzaamheid met de officiële lancering van het ambitieuze <strong style=\"color: black;\">'HOGENT Goes Green'</strong> project. Dit toekomstgerichte initiatief heeft als overkoepelend doel om alle HOGENT-campussen <strong style=\"color: black;\">volledig klimaatneutraal te maken tegen 2030</strong>, wat neerkomt op een reductie van 100% van de huidige CO2-uitstoot. Het project is het resultaat van twee jaar intensieve voorbereiding door een multidisciplinair team van duurzaamheidsexperts, ingenieurs, facility managers en studentenvertegenwoordigers.<br><br>De urgentie van klimaatactie is duidelijker dan ooit. Als onderwijsinstelling heeft HOGENT niet alleen de verantwoordelijkheid om bij te dragen aan een duurzamere samenleving, maar ook om het goede voorbeeld te geven aan de 15.000 studenten die door onze deuren gaan. Het 'HOGENT Goes Green' project omvat een investeringsenveloppe van 8,5 miljoen euro gespreid over vijf jaar, en raakt alle aspecten van het campusleven: van energie en gebouwen tot mobiliteit, afval, voedsel en groenvoorziening. Het is een holistische aanpak die alleen kan slagen met de actieve betrokkenheid van de hele HOGENT-gemeenschap.",
                    "<strong style=\"color: black;\">Energie en Gebouwen</strong><br><br>Een van de grootste pijlers van het project is de transitie naar hernieuwbare energie. Tegen 2027 worden alle daken van HOGENT-gebouwen uitgerust met <strong style=\"color: black;\">zonnepanelen</strong>, goed voor een totale capaciteit van 2,8 megawatt. Dit zal ongeveer 40% van het totale elektriciteitsverbruik dekken. De overige energie zal afkomstig zijn van gecertificeerde groene stroom. Daarnaast worden alle gebouwen grondig geïsoleerd, krijgen ze hoogefficiënte LED-verlichting met bewegingssensoren, en worden verouderde verwarmingssystemen vervangen door duurzame warmtepompen.<br><br>Ook waterbesparingsmaatregelen staan op de agenda: installatie van waterbesparende kranen en toiletten, en een regenwateropvangsysteem voor het onderhoud van de campustuinen. Deze maatregelen samen zullen het energieverbruik met 65% verminderen en het waterverbruik met 40%. Alle nieuwe bouwprojecten zullen voldoen aan de hoogste duurzaamheidsnormen (BREEAM Excellent certificering).",
                    "<strong style=\"color: black;\">Afval, Voedsel en Mobiliteit</strong><br><br>Op het gebied van afvalbeheer wordt er ingezet op drastische <strong style=\"color: black;\">plasticreductie</strong>. Alle single-use plastic producten worden gefaseerd uitgefaseerd: plastic flesjes, bestek, rietjes en verpakkingen. In de plaats komen duurzame alternatieven en waterfontijnen waar studenten gratis hun herbruikbare flessen kunnen vullen. Het recyclingsysteem wordt geoptimaliseerd met duidelijke, kleurgecodeerde afvalbakken op alle campussen. Doelstelling: 75% afvalrecyclage tegen 2028.<br><br>De campus cafetaria's en restaurants ondergaan een groenere transformatie. Het aanbod <strong style=\"color: black;\">vegetarische en vegan opties</strong> wordt verdubbeld, er komt een 'Veggie Monday' waarbij plantaardige maaltijden extra worden gepromoot, en alle voedselproducten worden waar mogelijk lokaal en biologisch ingekocht. Voedselverspilling wordt tegengegaan door samenwerking met Too Good To Go en donaties aan voedselbanken.<br><br>Duurzame mobiliteit krijgt een boost door uitbreiding van fietsenstallingen (we bespraken er al één eerder), stimulering van carpooling via een app, betere aansluiting op het openbaar vervoer, en het installeren van oplaadpalen voor elektrische auto's. Studenten en medewerkers die met de fiets of openbaar vervoer komen, krijgen kortingen in de cafetaria en bonuspunten.",
                    "<strong style=\"color: black;\">Groene Campus en Biodiversiteit</strong><br><br>Alle campussen krijgen een groenere make-over met de aanplant van honderden extra bomen, de creatie van groene daken en gevels, bijenhotels, insectenvriendelijke bloemenperken en zelfs een campusmoestuin waar studenten kunnen leren over duurzame voedselproductie. Deze maatregelen verhogen niet alleen de biodiversiteit en luchtkwaliteit, maar creëren ook aangename groene plekken waar studenten kunnen ontspannen en studeren.<br><br>De belangrijkste factor in dit hele project? <strong style=\"color: black;\">Jij!</strong> Studenten kunnen actief bijdragen door lid te worden van de <strong style=\"color: black;\">Green Team</strong>, een enthousiaste groep studenten die concrete projecten uitvoert: afvalopruimacties, upcycling workshops, duurzaamheidscampagnes, green challenges en meer. De eerste informatiesessie vindt plaats op <strong style=\"color: black;\">1 december 2025 om 18:00 uur</strong> in de grote aula van Campus Schoonmeersen. Er zijn ook verschillende studentbeurzen beschikbaar voor wie een duurzaamheidsproject wil uitwerken als onderdeel van hun studies.<br><br>Samen maken we het verschil voor een duurzame toekomst! Blijf op de hoogte via de website hogent.be/green of volg @hogentgoesgreen op Instagram. Voor vragen of ideeën: sustainability@hogent.be"
                },
                new List<string>
                {
                    "/img/banner18.webp",
                    "/img/banner19.webp"
                },
                DateTime.Now.AddDays(-6)
            )
        };

        dbContext.NewsItems.AddRange(newsItems);
        await dbContext.SaveChangesAsync();
    }
}